### ISSUE TITLE
Naming suggestions

### ISSUE THREAD

**Issue by pintariching** [pintariching/rustle#10]
Something that combines rust and svelte in some form? 
For some ideas, rust could be substituted with something to do with oxidation or perhaps the various types of rust: hematite, magnetite, wüstite
Svelte in English is used to describe a slender - thin appearance

**Comment by linrium** [comment]
How about stt stands for svelte typescript transformation

**Comment by AnupJoseph** [comment]
What about rusty-willow? Or slenderwear?

**Comment by ian-ok** [comment]
rvelte

**Comment by SameerSahu007** [comment]
What about Corrosion?
since svelte means thin and corrosion is the thin layer of oxygen and iron also known as rust

**Comment by LouisGariepy** [comment]
Maybe I'm just being plain, but I would argue that svelte-rs is probably the most discoverable and evident name for users.

The potential downside is that it might suggest that this project is somewhat "official". Personally I don't think it is a problem.

**Comment by 2nthony** [comment]
- readable: `rusvelte`, but I don't think it means to a compiler
- direct: `svelte-compiler-rs`, intutive

**Comment by codingjlu** [comment]
> What about Corrosion? since svelte means thin and corrosion is the thin layer of oxygen and iron also known as rust

Is this package planning to be published to npm? (The name is already [taken](https://www.npmjs.com/package/corrosion).)

**Comment by pintariching** [comment]
Let's move this into discussions #29 where I can add a poll.
