### ISSUE TITLE
Entities util duplicates in from_code

### ISSUE THREAD

**Issue by linrium** [pintariching/rustle#23]
In `src/compiler/parse/utils/entities.rs`. `from_code` method matches duplicate two codes to both `Entity::nbsp` and `Entity::NonBreakingSpace`. It will cause the second statement to be never reached.

160 => Entity::NonBreakingSpace,
160 => Entity::nbsp,

**Comment by pintariching** [comment]
Yeah I copied all the types directly from the [svelte repo](https://github.com/sveltejs/svelte/blob/master/src/compiler/parse/utils/entities.ts). Also, the code links to [this website](https://html.spec.whatwg.org/multipage/named-characters.html) where it notes

> It is intentional, for legacy compatibility, that many code points have multiple character reference names. For example, some appear both with and without the trailing semicolon, or with different capitalizations.
Maybe if the `Entities` enum is rewritten as a HashMap, that would be better?
