### ISSUE TITLE
Replacements for acorn functions

### ISSUE THREAD

**Issue by pintariching** [pintariching/rustle#32]
Are there any functions in [swc](https://github.com/swc-project/swc/tree/main/crates) that do the same functionality as the ones used in svelte from the package [acorn](https://github.com/acornjs/acorn). 
Specifically, here are the functions that are used from acorn:

- [x] [isIdentifierStart](https://github.com/acornjs/acorn/blob/11735729c4ebe590e406f952059813f250a4cbd1/acorn/src/identifier.js#L56)
- [x] [isIdentifierChar](https://github.com/acornjs/acorn/blob/11735729c4ebe590e406f952059813f250a4cbd1/acorn/src/identifier.js#L68)

**Comment by qwertydelle** [comment]
These functions are used internally in acorn and also exported so swc might have a version written internally for errors. The functions are also used in svelte for custom errors and parsing mustache tags. I think the only way is to implement our own, gonna keep digging to see if I see anything

**Comment by qwertydelle** [comment]
I think I found something similar [is_valid_start](https://rustdoc.swc.rs/swc_ecma_ast/struct.Ident.html#method.is_valid_start)

**Comment by pintariching** [comment]
And perhaps [verify_simbol](https://rustdoc.swc.rs/swc_ecma_ast/struct.Ident.html#method.verify_symbol) to replace isIdentifierChar?
As for implementing our own, acorn uses some auto generated regex. I think it shouldn't be a problem implementing it.

**Comment by qwertydelle** [comment]
I think the alternative to isIdentiferChar is [https://rustdoc.swc.rs/swc_ecma_ast/struct.Ident.html#method.is_valid_continue](is_valid_continue)
