### ISSUE TITLE
Understanding decode_character_references function

### ISSUE THREAD

**Issue by pintariching** [pintariching/rustle#33]
I would need some help understanding the `decode_character_references` function at [src/compiler/parse/utils/html.ts](https://github.com/sveltejs/svelte/blob/d5efa2e446d1f6a968ca8441936840da63a1a5d6/src/compiler/parse/utils/html.ts#L43)

What do the `(match, entity)` return? 
For starters, I think getting all the matches in a vector would be a good idea? Something like this in [src/compiler/parse/utils/html.rs](https://github.com/pintariching/rustle/blob/980607ed9cf589febd826edc184f41253d7ff7e4/src/compiler/parse/utils/html.rs#L42)

**Comment by qwertydelle** [comment]
`(match, entity)` returns a string

**Comment by pintariching** [comment]
So if I understand correctly, match is the whole matched string and entity is a list of separate strings?

**Comment by qwertydelle** [comment]
Seems like it

**Comment by qwertydelle** [comment]
Wait entity is a string corresponding to the first capture

**Comment by pintariching** [comment]
So `match` is the entire capture and `entity` is the first capture?

**Comment by pintariching** [comment]
After playing around, I found out that `match` is the current capture and `entity` a number at which the current `match` starts. I'm not sure then why the code does `entity[0]` as that returns `undefined`. I don't think you can index into a number?

Here is [the playground](https://www.typescriptlang.org/play?#code/MYewdgziA2CmB00QHMAUAoABNzAiALrBPpocaUSWfrvAE6wAO0AhsLKgPTWfIA0mVAFsW+YAAsBsMPgCW+AJ4BKTAF4AfJgDeWHHtCQYCJGhFjxSgNy692A1DiIUqaXMVWbt+0adpX8hQBtAAYAXQ9bHAZ8AFc6MDwaTz0AX08ldCUgA)

**Comment by pintariching** [comment]
Actually scratch that. [Here is another example](https://www.typescriptlang.org/play?ssl=19&ssc=2&pln=1&pc=1#code/DYUwLgBCB2YJbxAZwgXggbwFAEgDCA9gK6wgBOewBAxgNYDucSIhsxZAkqQOZkCGwAFwQAHAHYArBIA0uSjQZMWBNkU49+Q0ZIAssnABFiAI1AAZFdzMgAZmABKcbgAswAQTJkC9YQEYADABMAMx6WAC+ANxYWNQqSJAw8GAAngD6AA58YGDk0GgQ0CD0EPYg3ACiAB4ZABS4AAYAZLUAxAD8te2CVQDaADr99IMAJgC6ANQAPqPTACQYAPLGAFYg1GAAdLQgKUi1SQhwyACUmysEcNC1AORTNyfhJyddgpEz-cYnDfo33DdYE7RLAAIiarSq-RGUPosNG0JhUJGw0+ECahBIuQoVDojGYrDA7C4uV4AkiaNaGNI2IUeOUqnUJM0kRBmzIIAywD41BAB1gCHSWRyeWkEFqAFtstRnKLDqkTmgAHyYLAQNUQOLQJAEUCbKjcCVS5xA1XqzXa3X6vnJFIm9Ua+I6kB6ggGuUpXr+MZ2s2Oy2u60C3q+b3Re3ssBqfIgsAg01q8KAoA) with the regex that is used in the code.

In this case, both `match` and `entity` are strings of the current capture, but `entity` doesn't contain the first character or the `&` symbol.

**Comment by qwertydelle** [comment]
Yeah I think you got in also in the rust regev library the index 0 corresponds to the whole match while each subsequent index corresponds to a capture group
