### ISSUE TITLE
Implement mustache.rs

### ISSUE THREAD

**Issue by linrium** [pintariching/rustle#34]
Is there anybody working on it? If not I will do it.

**Comment by pintariching** [comment]
I'm currently not working on it, go ahead if you'd like!

**Comment by qwertydelle** [comment]
Made a pull request with a some types that might help writing mustache.rs and the other files in state.

**Comment by linrium** [comment]
I created a draft PR #37. I've got some issues with inner mutability. The original implement https://github.com/sveltejs/svelte/blob/master/src/compiler/parse/state/mustache.ts will mutable data inside the function. I tried to add lifetime, but it didn't work. So I tried `Rc` and `RefCell`, but it is pretty lengthy. Do you have any better ideas?
