### ISSUE TITLE
Implement crate rustle-code-red

### ISSUE THREAD

**Issue by pintariching** [pintariching/rustle#39]
There is a package called [code-red](https://github.com/Rich-Harris/code-red) that svelte uses for parsing some expressions with the functions in [src/compiler/parse/acorn.ts](https://github.com/sveltejs/svelte/blob/master/src/compiler/parse/acorn.ts).
I think the `code-red` package has to be rewritten in rust to be used in the parsing.

- [x] #40

**Comment by qwertydelle** [comment]
I do not think we need to implement the entirety of `code-red`. My reasoning behind this is the only functions from code-red used in svelte are [Parse](https://github.com/Rich-Harris/code-red/blob/master/src/index.js#L369) and [Parse Expression At](https://github.com/Rich-Harris/code-red/blob/master/src/index.js#L383). Both these functions require `Acorn ` which is a slightly different parser compared to `swc` and both functions in code-red seem to just be walking the AST generated by `Acorn`.
