### ISSUE TITLE
Replacement for Node

### ISSUE THREAD

**Issue by pintariching** [pintariching/rustle#40]
The type `Node` is used by rustle interfaces for the compile step and also in the `code-red` package in `handlers.js` The type definition is pulled from [@types/estree](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/estree/index.d.ts) however from an old version `0.0.50` which defined `Node` as 
```
export type Node =
    Identifier | Literal | Program | Function | SwitchCase | CatchClause |
    VariableDeclarator | Statement | Expression | PrivateIdentifier | Property | PropertyDefinition |
    AssignmentProperty | Super | TemplateElement | SpreadElement | Pattern |
    ClassBody | Class | MethodDefinition | ModuleDeclaration | ModuleSpecifier;
```

The new version defines `Node` as [this](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/05f701c1fe6d01b036fdc09c4449dc54788562a6/types/estree/index.d.ts#L38)

The problem is that in `swc_estree_ast` the `Node` enum has been [commented out](https://github.com/swc-project/swc/blob/e7c565dbb243b6a978f9d1bd7227fc2bcfb504a6/crates/swc_estree_ast/src/common.rs#L595) and I'm not sure where to pull the right type definitions.

**Comment by qwertydelle** [comment]
The right definition should be the `swc_estree_ast` since that's what we are gonna be using for parsing javascript .

**Comment by pintariching** [comment]
But that definition was commented out saying it's difficult to maintain

**Comment by qwertydelle** [comment]
But that is the only one you could use that I could think of since the `swc-ecma-parser` generates an AST that is not the same as other parsers like Acorn. I could be wrong so it is best to ask other people.

**Comment by pintariching** [comment]
I'll ask about in the 'swc' crate

**Comment by pintariching** [comment]
For now I've manually implemented all the remaining types in the `Node` enum.
