### ISSUE TITLE
Roadmap to 0.0.1 prerelease

### ISSUE THREAD

**Issue by pintariching** [pintariching/rustle#46]
I think we can have a pre release when we get the parsing working. Also perhaps implementing a basic CLI with a few commands that you can point to a .svelte file and it prints out the AST?

- [x] #55

**Comment by qwertydelle** [comment]
I agree

**Comment by qwertydelle** [comment]
How close are we to getting a full svelte file parsed? Is there anything else we need to add

**Comment by pintariching** [comment]
For a full svelte file a lot more stuff has to be added. More expressions need to be supported and classes dont work right now. Right now I think just the example works but I havent tried anything else.

**Comment by pintariching** [comment]
I tried publishing the project to crates.io but realised that a `rustle` project already exists [https://crates.io/crates/rustle](https://crates.io/crates/rustle).

**Comment by qwertydelle** [comment]
You could name it like how swc names their projects

**Comment by pintariching** [comment]
Ok, so for now, I'll publish the project as `rustle_lib` and `rustle_cli`. I would also like to try and ask @thomaslee if he would want to let us take over the `rustle` namespace on crates.io. I can't find his email anywhere, so I guess I'll try and ping him with this comment?
