### ISSUE TITLE
Assignment inside function call?

### ISSUE THREAD

**Issue by pintariching** [pintariching/rustle#47]
What is this line [here](https://github.com/sveltejs/svelte/blob/7331c06a74622a4635968a0c8d87b91fda4a1110/src/compiler/parse/index.ts#L170) doing?
```
const identifier = this.template.slice(this.index, this.index = i);
```
I can't figure out what the `this.index = 1` means. Does it assign `i` to `this.index`?

**Comment by linrium** [comment]
for example, this.index equals 1, and I equal 2, then the slice method will be .slice(1, 2). This is a short syntax.

**Comment by pintariching** [comment]
Here's [a fiddle](https://www.typescriptlang.org/play?#code/DYUwLgBAbghsCuIIF4ICIYWAewHYHMIBnMAJwEsCIBjPMGSywgd21IBMi0AoUSS9iAAeKCACZutXEWygAdDnwAKWAhByiwctRBKBwgDQR9I1AA4AlBcl4Z8xXtyCh1m9NnqHqxBq07HzkYmogCMAAxWbnae2MomFkA). Appearently this does assign `i` to `this.index` and uses this new value as a parameter to the `.slice` function.
