### ISSUE TITLE
Implement a CLI

### ISSUE THREAD

**Issue by pintariching** [pintariching/rustle#55]
I think a simple CLI is the last piece missing before doing a prerelease. I think it should just accept a file or a directory and call the `rustle::compile_file_to_js` function. For now I think if anything goes wrong it should just panic.

Does anybody want to work on it or has any other suggestions?

**Comment by qwertydelle** [comment]
How would the CLI behave when a directory is passed instead of a file? split if it should compile every file in the directory or a specific file it looks for.

**Comment by pintariching** [comment]
I think it should look for all files that end in .rustle and compile them to a directory named `build`. Maybe make the output directory name configurable?

**Comment by qwertydelle** [comment]
I am currently working on it

**Comment by qwertydelle** [comment]
Could you add a parse function to rustle that could be used in the CLI?
