### ISSUE TITLE
missing support for native attribute?

### ISSUE THREAD

**Issue by Stvchm9703** [pintariching/rustle#57]
hi there! it is great to see your great work!
BTW, I try rustle around and find out it cannot parse the HTML DOM attribute

```html
<button on:click={increment}>Increment</button>
<span>
<!-- this ok -->
  <div bind:class={'q'}>{counter}</div>

<!-- this fail -->
  <div class="q">{counter}</div>
</span>
<button on:click={decrement}>Decrement</button>
```

hope this help you, thank

**Comment by pintariching** [comment]
Hi, thanks! :D
Yes, other attributes still need to be implemented. Currently only the `on:click` attribute is supported, everything else is still under development.

**Comment by pintariching** [comment]
This should work now in the latest release
