### ISSUE TITLE
How to test?

### ISSUE THREAD

**Issue by jimafisk** [pintariching/rustle#59]
Awesome project, thanks for taking this on :tada: 

I assumed I could create an `app.rustle` file with the following contents:

```svelte
<script>
  let test = "test";
</script>

<h1>{test}</h1>
```

Then run `rustle_cli app.rustle` to create a compiled `app.js` file, but that throws:

```
thread 'main' panicked at 'Parse error: expecting ={', /home/jimafisk/.cargo/registry/src/github.com-1ecc6299db9ec823/rustle_lib-0.0.1-alpha/src/compiler/parse/parser.rs:120:13
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Comment by pintariching** [comment]
I've moved the library crate from `rustle_lib` to `rustle` namespace on [crates.io](https://crates.io/crates/rustle) and `rustle_cli 0.0.1-alpha` depends on that namespace. I'm still learning and it's possible I've messed some things up on crates.io.
Can you try updating the `rustle_cli` binary with `cargo install rustle_cli --version "0.0.2-alpha"`

**Comment by jimafisk** [comment]
Thanks for the cargo command, I'm unfamiliar with Rust. That ran a build that completed with:

```
Compiling rustle v0.0.1-alpha
Compiling rustle_cli v0.0.2-alpha
Finished release [optimized] target(s) in 12m 17s
Replacing /home/jimafisk/.cargo/bin/rustle_cli
Replaced package `rustle_cli v0.0.1-alpha` with `rustle_cli v0.0.2-alpha` (executable `rustle_cli`)
```

Running `which rustle_cli` returns `/home/jimafisk/.cargo/bin/rustle_cli`

However `rustle_cli --version` still says `Rustle 0.0.1-alpha`

**Comment by pintariching** [comment]
Oh whoops, I forgot to update the version in the CLI crate. Running `--version` with the `0.0.2-alpha` version is going to return `0.0.1-alpha`.
I just saw the error and tried it out, and it appears that `<h1>` tags don't work and return that error. Try using a `<div>` instead, that should work.

**Comment by jimafisk** [comment]
Using a `<div>` worked! Very exciting! Can't wait for more, awesome job so far :)

**Comment by pintariching** [comment]
Thank you for bringing this issue to my attention, I haven't realised that only div tags work. I'll look into it!

**Comment by qwertydelle** [comment]
@pintariching the issue seems to be caused when trying to parse attributes.

**Comment by pintariching** [comment]
Maybe the number in the tag is throwing the parser off? If you'd like you can look into it.

**Comment by qwertydelle** [comment]
I skimmed through the part of the parser that handles attributes and seems it doesn't have conditions for parsing normal html attributes .

**Comment by qwertydelle** [comment]
Looked through here to see how the svelte compiler parses attributes [tag.ts](https://github.com/sveltejs/svelte/blob/146e7a6310627d4599bb60760d573dffa5d1d2ce/src/compiler/parse/state/tag.ts#L298)

**Comment by qwertydelle** [comment]
Currently busy I could look into it later though.

**Comment by pintariching** [comment]
No worries, I'll take a look at it tomorrow.

**Comment by pintariching** [comment]
This should work now
