### ISSUE TITLE
General utilities rewrite

### ISSUE THREAD

**Issue by pintariching** [pintariching/rustle#7]
One place to start would be rewriting all the utilities from here: [https://github.com/sveltejs/svelte/tree/master/src/compiler/utils](https://github.com/sveltejs/svelte/tree/master/src/compiler/utils)

A lot of them are used further up in the parsing and compiling. 

- [x] error.ts
- [ ] extract_svelte_ignore.ts
- [ ] flatten.ts
- [x] full_char_code_at.ts
- [x] fuzzymatch.ts
- [x] get_code_frame.ts
- [ ] link.ts
- [ ] list.ts
- [ ] mapped_code.ts
- [x] names.ts
- [x] namespaces.ts
- [ ] nodes_match.ts
- [x] patterns.ts

**Comment by Antonio-Bennett** [comment]
I would love to help with this :)

**Comment by pintariching** [comment]
@Antonio-Bennett Feel free to open a PR on anything you like 😁

**Comment by Antonio-Bennett** [comment]
@pintariching okay thanks! Anything you're currently working on that I shouldn't duplicate?

**Comment by pintariching** [comment]
Most of it is commited to main right now, so feel free to pick up anything

**Comment by linrium** [comment]
I need to review the PR implement locate_character module before implementing the `error` :)

**Comment by humancalico** [comment]
- trim.ts
	- contains two functions `trim_start` and `trim_end` I suppose we won't need these since Rust standard library already has these [[1](https://doc.rust-lang.org/std/string/struct.String.html#method.trim_start)] [[2](https://doc.rust-lang.org/std/string/struct.String.html#method.trim_end)] 
- push_array.ts
	- Same. Already implement in Rust standard library

**Comment by pintariching** [comment]
Yeah that makes sense. No point in implementing these.

**Comment by mplayer78** [comment]
Hi there, I'd love to help with this (although I am pretty new to rust). It occurs to me that some of these functions will not be required as Rust's type safety will handle them at a higher level. For example the flatten function will take [1, [2, 3, [4, 5]]] => [1, 2, 3, 4, 5] but this would be challenging to even create a vec with this shape. It seems that we'd be doing some funny encoding (and wrapping stuff in Boxes) to just decode it after?? (Excuse me if I have completely missed some very basic concept in Rust!!)

**Comment by pintariching** [comment]
It could be that the `flatten` function doesn't need to be used as with `trim_start` and `trim_end`. I haven't seen where it's used yet. If you're new and want a challenge you can try and implementing it as a challenge, but know that it may not be used :sweat_smile:

**Comment by mplayer78** [comment]
Hi there, I have reimplemented the fuzzymatch utility but am struggling to push the branch (access rights).
