### ISSUE TITLE
Choosing the parsing backend

### ISSUE THREAD

**Issue by pintariching** [pintariching/rustle#9]
Some options are:

- [nom](https://github.com/geal/nom)
- [chumsky](https://github.com/zesterer/chumsky)
- [combine](https://github.com/marwes/combine)
- [pest](https://lib.rs/crates/pest)

`nom` and `pest` seem to be the most popular right now.
Any other suggestions? Tell me what we should use

**Comment by linrium** [comment]
I found a benchmark between chumsky and nom: https://github.com/zesterer/chumsky/pull/94
And some related topics between nom and pest: https://unhandledexpression.com/general/2018/10/04/no-pest-is-not-faster-than-nom.html

**Comment by pintariching** [comment]
Chumsky seems well maintained and apparently very fast. I'm leaning towards it.

**Comment by qwertydelle** [comment]
From looking into [Svelte Parser](https://github.com/sveltejs/svelte/tree/master/src/compiler/parse) HTML is parsed using its own parser while javascript an CSS are both parsed by 3rd party libraries. Rustle could use a similar approach by parsing javascript with [swc_ecma_parser](https://docs.rs/swc_ecma_parser/latest/swc_ecma_parser/) or another parser and CSS with another library.

**Comment by pintariching** [comment]
Yeah after looking into it, I think I'm going to use the [swc](https://github.com/swc-project/swc) crates for parsing the js and css and try and rewrite their html compiler

**Comment by qwertydelle** [comment]
Does swc have a css parser?

**Comment by pintariching** [comment]
I looked around in the swc crates and [I found it](https://github.com/swc-project/swc/tree/main/crates/swc_css_parser)
